### ISSUE TITLE
Demos in homepage do not work.

### ISSUE THREAD

**Issue by tuupola** [bitbonsai/facyBox#13]
Demos at [homepage](http://bitbonsai.com/facybox/) do not work. Probably because page throws the following JavaScript error: `Uncaught TypeError: Cannot read property 'msie' of undefined`

**Comment by bitbonsai** [comment]
Thanks for the callout. jQuery 1.9 removed support for $.browser, breaking the code. I've added 1.8.3 from CDN and a disclaimer stating that.
