### ISSUE TITLE
Facybox title below image

### ISSUE THREAD

**Issue by XavierF** [bitbonsai/facyBox#14]
Is there a way for facybox to display image title from a href attribute below the image?
also to add additional content such as social media links?

currently have it working in a wordpress installation using jquery Isotope for laying out images(or posts in the loop).

with this:

``` html
<a href="#" rel="box" class="item" title="<?php the_title();?>"><?php the_content();?></a>
```

``` javascript
<script>
$("a[href$='.jpg'], a[href$='.png'], a[href$='.jpeg'], a[href$='.gif']").facybox();
</script>
```

**Comment by ghost** [comment]
I think there is no way to view title at all in this minimal version.

Only 1 question: why for this files?
> fancy_title_left.png
> fancy_title_main.png
> fancy_title_right.png

**Comment by bitbonsai** [comment]
The pngs were for decorating the title, this plugin was created more than 4 years ago :)
