### ISSUE TITLE
facybox Ignores the Content-Type header

### ISSUE THREAD

**Issue by packetmonkey** [bitbonsai/facyBox#2]
When trying to display an image without an extension (e.g. by using send_file in a rails application for securing access to that file) facybox will ignore the Content-type header returned by the web server and display garbage to the end user. facyBox should instead also include a list of recognized mime types that it knows are images that can be displayed inline, similar to the imageTypes setting and display those images inline.

**Comment by packetmonkey** [comment]
Altering the revealAjax function to below should provide this functionality while maintaining the current behavior of the function as well. The downside of this method is it will download the image twice, once to check the content-type header and the second time from the properly called revealmage function. These two functions I would image should probably be merged so only one response is needed. I can also if you would like fork the repo and make a pull request for this change if you decide to use it and it would be eaiser.

`settings: {
        opacity         : 0.3,
        overlay         : true,
        modal           : false,
        imageTypes      : [ 'png', 'jpg', 'jpeg', 'gif' ],
                imageMimeTypes  : [ 'image/jpeg', 'image/png', 'image/gif' ]
    },

  function revealAjax(href) {
    $.ajax({
      type: "GET",
      url: href,
      complete: function(XMLHttpRequest, textStatus) {
        content_type = XMLHttpRequest.getResponseHeader("Content-Type");
        if ( jQuery.inArray(content_type, $.facybox.settings.imageMimeTypes) >= 0 ) {
          revealImage(href)
      $.facybox.centralize();
        } else {
          $.facybox.reveal( XMLHttpRequest.responseText );
        }
      }
    });
  }

`

**Comment by bitbonsai** [comment]
Thanks, added to the core. Since I don't develop in Rails, couldn't test it, so if there's any issue please let me know. Done
