### ISSUE TITLE
Preloading images in Firefox doesn't work

### ISSUE THREAD

**Issue by rmm5t** [bitbonsai/facyBox#3]
Firefox wasn't preloading images because the regex used to pull the image URL out of the background-image CSS didn't cover the format that Firefox uses (surrounding double quotes).  This branch fixes this problem.

http://github.com/rmm5t/facyBox/tree/fix_preload_images

Relelvant commit:

http://github.com/rmm5t/facyBox/commit/a3ce2866171ac612f6b3b75770f8ae58a66c7331

**Comment by kevinzen** [comment]
Thanks for submitting this patch. I cut/pasted the changed line into my project and it fixed the issue for me as well.

**Comment by bitbonsai** [comment]
This issue was closed with a pull from cco3 that prevents background-image: none to being fetched...
